Feat/move bot to classes
kuznevia/pollbot pull request #21
Opened 2024-11-12 15:36 UTC by kuznevia

2024-11-12 19:55 UTC, meloshnikov requested changes

2024-11-12 19:55 UTC, meloshnikov commented on src/DB.ts
> +require('dotenv').config({
давай попробуем твой require dotenv изолировать по всему приложению.

import { envConfig } from './env-config';


попробуй наверни что то похожее
// env-config.ts
```
import dotenv from 'dotenv';

class EnvConfig {
  private static instance: EnvConfig;
  private envVariables: Record<string, string>;

  private constructor() {
    dotenv.config();
    this.envVariables = Object.fromEntries(
      Object.entries(process.env).filter(([_, value]) => value !== undefined)
    );
  }

  public static getInstance(): EnvConfig {
    if (!EnvConfig.instance) {
      EnvConfig.instance = new EnvConfig();
    }
    return EnvConfig.instance;
  }

  public get<T>(key: string): T {
    const value = this.envVariables[key];
    if (value === undefined) {
      throw new Error(`Environment variable ${key} is not set`);
    }
    return value as T;
  }
}

export const envConfig = EnvConfig.getInstance();
```
юзаем
const mongoUri = envConfig.get<string>('MONGO_URI');

2024-11-12 19:55 UTC, meloshnikov commented on src/features/poll/games/games.ts
>    cron.schedule('0 11 * * *', async () => {
Вынеси в константу с хорошим именованием и не надо будет комментариев
`// Каждое утро в 11:00 мск  = '0 11 * * *'`

2024-11-12 19:55 UTC, meloshnikov commented on src/features/poll/games/poll.ts
> +      sender === 'Alexey' || sender === 'Viacheslav' || sender === 'Никита';
Создай лист разрешенных коучей и проверяй входит или нет, потом расширять будет проще

2024-11-12 19:55 UTC, meloshnikov commented on src/features/poll/games/poll.ts
> +    if (sender && !isCoachOrOwner) {
назови переменную **hasNoPermissionCreateSurvey** в ней выполни проверки получится что то типа: `CoachOrOwners[sender]` вместо `(sender && !isCoachOrOwner)`
уже будет проще читаться `if (hasNoPermissionCreateSurvey)`

2024-11-12 19:55 UTC, meloshnikov commented on src/features/poll/games/poll.ts
> +        }
чет ифов много, читается тяжело, надо бы пересмотреть логику.

2024-11-12 19:55 UTC, meloshnikov commented on src/features/poll/practice/poll.ts
> +    if (sender && !isMondayOrThursday()) {
если отправителя нет, можно зарежектить сразу вначале, потом спокойно описывать все условия.

2024-11-12 20:07 UTC, meloshnikov commented on src/bot/bot.ts
> +      const sender = msg.from?.first_name;
напиши уже тулзу на извлечение chatId как минимум в 6 местах пишешь эту конструкцию.

2024-11-13 14:22 UTC, meloshnikov approved these changes

2024-11-13 14:22 UTC, meloshnikov commented on src/features/poll/games/games.ts
> +
Если ты проверяешь если завтра игры, то
```
 tommorrowGames = await checkGameTomorrow(); 
  if (tommorrowGames.length) { 
......
}
```

замени const hasGamesTomorrow = await checkHasGamesTomorrow(); возвращай boolean если с самими играми ниче не делаешь, а можешь сразу в объекте два ключа отдавать  { hasGamesTomorrow, games }
и где надо используешь 
```
if (hasGamesTomorrow) {
    console.log('Пробую автоматически отправить опрос на игру');
    sendGamePoll(bot, Number(chatId), botName);
  } else {
    console.log('Завтра нет игр');
  }
```

2024-11-13 14:22 UTC, meloshnikov commented on src/features/poll/practice/poll.ts
>        );
а че ты отрицание убрал? случайно зацепил?

2024-11-13 14:22 UTC, meloshnikov commented on src/shared/utils/utils.ts
> +  sender === botName;
так разве не лучше ?
`export const isAdminOrBot = (sender?: string) => [ coachName, creatorName, ownerName, botName].includes(sender)`

2024-11-14 13:33 UTC, kuznevia commented on src/features/poll/practice/poll.ts
>        );
случайно да, вернул

2024-11-18 08:41 UTC, merged